# Generated by Django 2.0.2 on 2018-03-11 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_id', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=12)),
                ('os', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=100)),
                ('mem', models.CharField(max_length=50)),
                ('eth', models.CharField(max_length=200)),
                ('is_virtaul', models.CharField(max_length=50)),
                ('salt_key', models.CharField(blank=True, max_length=50, null=True)),
                ('salt_status', models.CharField(choices=[('ok', '正常'), ('error', '错误')], default='ok', max_length=10)),
                ('admins', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Category')),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hostgroup',
            },
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('form_type', models.CharField(choices=[('optional', '可选'), ('required', '必填')], default='optional', max_length=30)),
                ('is_must', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('is_search', models.BooleanField(default=True)),
                ('optional_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(blank=True, to='cmdb.HostGroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='props',
            field=models.ManyToManyField(to='cmdb.Prop'),
        ),
    ]
