# Generated by Django 2.0.2 on 2018-03-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180312_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prop',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='is_edit',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='is_must',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='is_search',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='is_show',
        ),
    ]
