# Generated by Django 2.0.2 on 2018-02-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admins.Menu')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'operation',
            },
        ),
        migrations.RemoveField(
            model_name='perm',
            name='module',
        ),
        migrations.AddField(
            model_name='operation',
            name='perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Perm'),
        ),
        migrations.AddField(
            model_name='menu',
            name='perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.Perm'),
        ),
    ]
