# Generated by Django 2.0.2 on 2018-02-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20180227_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='perm',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='perm',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
