# Generated by Django 2.0.2 on 2018-03-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_perm_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(blank=True)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
