# Generated by Django 2.0.2 on 2018-03-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perm',
            name='menu',
        ),
        migrations.AddField(
            model_name='perm',
            name='module',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
